package org.proteinevolution.knime.porttypes.structure;

import org.knime.core.data.DataType;
import org.knime.core.node.InvalidSettingsException;
import org.knime.core.node.ModelContentRO;
import org.knime.core.node.ModelContentWO;
import org.knime.core.node.port.AbstractSimplePortObjectSpec;
import org.knime.core.node.port.image.ImagePortObject;


/**
 * 
 * @author lzimmermann
 *
 */
public final class StructurePortObjectSpec extends AbstractSimplePortObjectSpec {

	/**
     * @noreference This class is not intended to be referenced by clients.
     */
    public static final class Serializer extends AbstractSimplePortObjectSpecSerializer<StructurePortObjectSpec> {}
    
    private static final String CFG_NO_STRUCTURES = "CFG_NO_STRUCTURES";
	
	private DataType m_type;
	private int nStructures;
    	
	public StructurePortObjectSpec(final DataType type, final int nStructures) {
		
		this.m_type = type;
		this.nStructures = nStructures;
		
		if (this.nStructures < 1) {
			
			throw new IllegalArgumentException("No. of structures must be at least 1!");
		}
		
		if (this.m_type == null) {
			
			throw new NullPointerException("Argument must not be null.");
		}
	}
	
	  /** <b>Framework constructor - do not use.</b> The constructor is required
     * by the super class implementation to restore the content. Client code
     * must not call this constructor. */
    public StructurePortObjectSpec() {
        // no op
    }
	
	/** Get the {@link DataType} of the cell that will be generated by the
     * port objects {@link ImagePortObject#toDataCell()} method.
     * @return The type of the cell, never null. */
    public DataType getDataType() {
        return this.m_type;
    }
    
    public int getNStructures() {
    	
    	return this.nStructures;
    }

    /** {@inheritDoc} */
	@Override
	protected void load(final ModelContentRO model) throws InvalidSettingsException {
		
		this.m_type = DataType.load(model);
		this.nStructures = model.getInt(CFG_NO_STRUCTURES);
	}
	
	 /** {@inheritDoc} */
    @Override
    protected void save(final ModelContentWO model) {
    	
        this.m_type.save(model);
        model.addInt(CFG_NO_STRUCTURES, this.nStructures);
    }
}
 